spring:
  application:
    name: eureka-server
    
server:
  port: 2001
  
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka1
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultzone: http://${eureka.instance.hostname}:${server.port}/eureka/

