spring:
  application:
    name: config-server
  sleuth:
    sampler:
      probability: 1
  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LiuZhen1999/SpringCloud
          searchPaths: config
    
server:
  port: 6001
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      